import { PeAssessmentInput } from './types';

export const DEFAULT_INPUT: PeAssessmentInput = {
  pesi: {
    ageYears: 60,
    male: false,
    cancer: false,
    heartFailure: false,
    chronicLungDisease: false,
    heartRateBpm: 90,
    systolicBpMmHg: 120,
    respiratoryRatePerMin: 18,
    temperatureC: 37,
    alteredMentalStatus: false,
    spo2Percent: 96,
  },
  hemodynamics: {
    cardiacArrest: false,
    persistentHypotension: false,
    transientHypotension: false,
    vasopressorOrInotropeRequired: false,
    normotensiveShockSigns: false,
  },
  respiratoryModifiers: {
    spo2Below90: false,
    respRateAtOrAbove30: false,
    supplementalO2Above6L: false,
    nonrebreatherOrNIV: false,
    hypoxemicOrVentilatoryFailure: false,
  },
  rvAndBiomarkers: {
    rvDysfunctionOnImaging: 'not_done',
    troponinElevated: 'not_done',
    bnpOrNtProBnpElevated: 'not_done',
    rightHeartThrombus: false,
    concomitantDvt: false,
    subsegmentalOnly: false,
    singleSmallDefectNoOtherThrombus: false,
  },
  bleedingRisk: {
    absoluteContraindication: false,
    highBleedingRisk: false,
  },
  outpatientEligibility: {
    requiresSupplementalO2: false,
    requiresNarcoticsForPain: false,
    respiratoryDistress: false,
    abnormalPulseOrBp: false,
    recentBleedingOrRiskFactors: false,
    seriousComorbidity: false,
    poorMentalStatusOrSupport: false,
    needleAverseNoLmwhAccess: false,
    noAccessToDoacs: false,
  },
  specialPopulations: {
    pregnant: false,
    activeMalignancy: false,
    suspectedOrConfirmedHit: false,
    antiphospholipidSyndrome: false,
    inheritedThrombophiliaSuspected: false,
    inheritedThrombophiliaKnownType: 'none',
    unprovoked: false,
    recurrentOnTherapeuticAnticoagulation: false,
  },
};
